### ISSUE TITLE
Windows build is broken

### ISSUE THREAD

**Issue by karwa** [apple/swift-system#92]
```
D:\a\swift-url\swift-url\.build\checkouts\swift-system\Sources\System\FileOperations.swift:445:7: error: cannot find 'system_ftruncate' in scope
```

😐

I don't like it when my builds break because `swift-system` published a release without even testing it. Please never do that again.

**Comment by lorentey** [comment]
I reverted the offending commit in #93. I'll tag a point release once I verify this resolves this issue.

**Comment by karwa** [comment]
Thanks @lorentey 

I'm sorry to be like this, but it's just too much all the time. I'll take the hit and lose some friends if it shocks the system enough to get things fixed.

**Comment by lorentey** [comment]
Noted.

**Comment by lorentey** [comment]
Version 1.2.1 is out fixing the Windows port.
