### ISSUE TITLE
1.6.0 doesn't build on Linux with a 6.2 Swift compiler

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-system#238]
You can see this on https://swiftpackageindex.com/apple/swift-system/builds, there are errors like:

```
/host/spi-builder-workspace/Sources/System/IORing/IORing.swift:874:18: error: a mutating method cannot return a ~Escapable result
872 |     @inlinable public var mutableBytes: MutableRawSpan {
873 |         @_lifetime(&self)
874 |         mutating get {
    |                  `- error: a mutating method cannot return a ~Escapable result
875 |             let span = MutableRawSpan(_unsafeBytes: unsafeBuffer)
876 |             return unsafe _overrideLifetime(span, mutating: &self)
```

It also triggers warning about using regular imports and `@_implementationOnly import` directives:

```
/host/spi-builder-workspace/Sources/System/IORing/IOCompletion.swift:4:8: warning: 'CSystem' inconsistently imported as implementation-only
 2 | #if os(Linux)
 3 |
 4 | import CSystem
   |        `- warning: 'CSystem' inconsistently imported as implementation-only
 5 |
 6 | public extension IORing {
/host/spi-builder-workspace/Sources/System/Internals/CInterop.swift:16:29: note: imported as implementation-only here
14 | import ucrt
15 | #elseif canImport(Glibc)
16 | @_implementationOnly import CSystem
   |                             `- note: imported as implementation-only here
17 | import Glibc
18 | #elseif canImport(Musl)
```

**Comment by Lukasa** [comment]
Yep, this comes from the IORing changes that also caused the other two breakages you can see on the tracker: #240 #237

**Comment by jrflat** [comment]
https://swiftpackageindex.com/apple/swift-system/builds is currently using `registry.gitlab.com/finestructure/spi-images:basic-6.2-latest` image with `swift-6.2-DEVELOPMENT-SNAPSHOT-2025-05-30-a` toolchain, which I think is a bit too old for the language features used. I think this should be resolved when the image is updated to a newer toolchain.

**Comment by glessard** [comment]
When Swift Package Index update their 6.2 snapshot to one that supports the `Lifetime` experimental feature, then swift-system will be green with that compiler. I will close this issue since there is nothing much we can do on our side.

**Comment by glessard** [comment]
In https://github.com/apple/swift-system/pull/249, we gated the feature which requires a 6.2 compiler behind a feature flag. This will prevent pre-release 6.2 compilers which are not complete 6.2 compilers from failing to compile.
